apiVersion: v1
kind: Service
metadata:
  name: ts-route-service
  namespace: train-ticket-test
spec:
  selector:
    app: ts-route-service
  ports:
    - name: http
      port: 11178
      targetPort: http
