apiVersion: v1
kind: Service
metadata:
  name: ts-travel-service
  namespace: train-ticket-test
spec:
  type: NodePort
  selector:
    app: ts-travel-service
  ports:
    - name: http
      port: 12346
      targetPort: http
      nodePort: 30046
