apiVersion: v1
kind: Namespace
metadata:
  name: jenkins-agents
---
apiVersion: v1
kind: Namespace
metadata:
  name: buildkit
---
apiVersion: v1
kind: Namespace
metadata:
  name: registry
---
apiVersion: v1
kind: Namespace
metadata:
  name: train-ticket-prod
